"""empty message

Revision ID: 9c70923d093f
Revises: 73e22b371c3a
Create Date: 2024-03-06 22:29:15.714307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c70923d093f'
down_revision = '73e22b371c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('diameter', sa.String(length=250), nullable=True),
    sa.Column('gravity', sa.String(length=250), nullable=True),
    sa.Column('terraine', sa.String(length=250), nullable=True),
    sa.Column('climate', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planets')
    op.drop_table('favorites_planets')
    op.drop_table('favorite_people')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('birth_day', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=250), nullable=True))
        batch_op.alter_column('height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.drop_constraint('people_name_key', type_='unique')
        batch_op.drop_constraint('people_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('people_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.create_unique_constraint('people_name_key', ['name'])
        batch_op.alter_column('eye_color',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.String(length=250),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('hair_color')
        batch_op.drop_column('birth_day')
        batch_op.drop_column('weight')
        batch_op.drop_column('full_name')

    op.create_table('favorite_people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='favorite_people_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_people_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_people_pkey')
    )
    op.create_table('favorites_planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='favorites_planets_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_planets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_planets_pkey')
    )
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('climate', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('diameter', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planets_pkey'),
    sa.UniqueConstraint('name', name='planets_name_key')
    )
    op.drop_table('favorites')
    op.drop_table('planet')
    # ### end Alembic commands ###
